services:
  db:
    image: postgres:15

    container_name: kaza_shop_db

    restart: always

    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kaza_shop

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .

    container_name: kaza_shop_app

    depends_on:
      - db

    env_file:
      - .env

    ports:
      - "8080:8000"

    volumes:
      - ./media:/app/media

    restart: always

volumes:
  postgres_data: